### PR TITLE
Result page

### PR DESCRIPTION
**Pull request by rahulyadav139**
I have created result page for this project. Kindly review it.

### CODE REVIEW

**Review by Ananyamadhu08 — APPROVED** [review]
looks good can go ahead and merge 🤙

**Comment by shruthipatil11** [comment]
Looks very good.

Just add details in meta tag(author and page description) inside head .

<div class="question-answer__answers">
            <div class="answer">Ester Sunday</div>
            <div class="answer">Epiphany</div>
            <div class="answer">All Souls’ Day</div>
            <div class="answer correct-answer">Christmas Day</div>
 </div> - Here, I think we can access each div using "question-answer__answers div" in css and don't need to add class to each child element only if there 'answer' class is not being used anywhere else.

**Comment by rahulyadav139** [comment]
> Looks very good.
> 
> Just add details in meta tag(author and page description) inside head .
> 
> Ester Sunday
> Epiphany
> All Souls’ Day
> Christmas Day
> - Here, I think we can access each div using "question-answer__answers div" in css and don't need to add class to each child element only if there 'answer' class is not being used anywhere else.

Thank you for the review. Yes, we can access child div by using parent class and yes if these child class is not being used anywhere else I should omit them. For now, I am keeping the way it way but in future, I keep that in mind. And I am not aware of these meta tags let me read about these. Definitely, I will add these after understanding it.

**Comment by shruthipatil11** [comment]
Looks good to merge

**Pull request merged**
