### PR TITLE
Instruction page

### PR DESCRIPTION
**Pull request by rahulyadav139**
I have created instruction page for this project. Kindly review it.

### CODE REVIEW

**Review by Ananyamadhu08 — APPROVED** [review]
looks good to go 👍

**Review by Ananyamadhu08 — APPROVED** [review]
looks good 👍

**Review by j24m — APPROVED** [review]
Same suggestion here too, the border radius of the button can be decreased ? And same margin on top and bottom of the quiz box.  Please refrain from making such long PRs and adding so many files to a single  PR.

**Comment by rahulyadav139** [comment]
> 

I will keep that in mind. In future, I will create PR for moderate file changes.

**Pull request merged**
